# Generated by Django 4.2.2 on 2023-08-08 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(upload_to='blog/imgs')),
                ('año', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
