# Generated by Django 4.2.2 on 2023-08-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='porfolio/imgs/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
